name: SeikatsuSabaPlugin
version: ${project.version}
main: net.kunmc.lab.seikatsusabaplugin.SeikatsuSabaPlugin
api-version: 1.16
authors: [Peyang]
description: 生活鯖用のプラグイン
website: https://kunmc.net/

commands:
  head:
    description: プレイヤの頭をチョンパします！
  hat:
    description: プレイヤーやアイテムをかぶります。
  unhat:
    description: かぶっているエンティティやアイテムをぬぎます。
permissions:
  seikatsu.head:
    description: プレイヤの頭をチョンパします！
    default: true
  seikatsu.hat:
    description: プレイヤーやアイテムをかぶります。
  seikatsu.hat.item:
    description: アイテムをかぶります。
    default: true
  seikatsu.hat.entity:
    description: エンティティをかぶります。
    default: true
  seikatsu.hat.player:
    description: プレイヤーをかぶります。
    default: op
  seikatsu.unhat:
    description: かぶってるエンティティやアイテムを脱ぎます。
    default: true
  seikatsu.mention.use:
    description: メンションを飛ばせます。
    default: true
  seikatsu.mention.bypass:
    description: メンションの影響を受けません。
    default: op
